### ISSUE TITLE
import Wallet Bug

### ISSUE THREAD

**Issue by mcwithimp** [Cryptonomic/Tezori#139]
Hi, 

I am testing Cryptonomic in dev and release also. 
There are some issue when importing an existing wallet.

**Issue**
 When user import an existing wallet and he/she put a passphrase, 
   validations can not capture all cases
   following cases emit an error which users can not notice so they are likely to just wait
     case1: user input invalid but more than 8 lengths of passphrase
     case2: user input valid but incorret passphrase 
   where 'valid' means that a passphrase must include:
        - at least 8 characters
        - 1 upper case
        - 1 lower case
        - 1 speacial chracter
        - 1 number

**Suggestion**
 1) add a type of invalid passphrase for case1 in validations
      (line 116 at app/reducers/walletInitialization.duck)
```
   const validations = [
      { value: walletLocation, type: 'locationFilled' },
      { value: `${walletLocation}/${walletFileName}`, type: 'validJS' },
      { value: password, type: 'notEmpty', name: 'Password' },
      { value: password, type: 'minLength8', name: 'Password' }
      #add this
      { value: password, type: 'invalid', name: 'Password' }
    ]
```
  2) return wrongPassphrase and notify users of this, then wait user inputs again
       (in TesozWallet.ts from conseiljs)
`const keys = <KeyStore[]>JSON.parse(CryptoUtils.decryptMessage(encryptedKeys, passphrase, salt));`

**Comment by vishakh** [comment]
Thanks for the bug report. Could you please retest after #130 is done and we will assign this ticket to a dev if the issue still persists?

**Comment by vishakh** [comment]
@mcwithimp Now that #130 is closed, do you still have this issue?
