### ISSUE TITLE
Transactions Tab - Implementation and Improvement

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezori#145]
We currently can't get the status of the transaction but we do have the rest of the information in the design.

Design:
https://zpl.io/a74dyPj

**Comment by polinasoshkina** [comment]
@yanivkalfa I am updating this ticket with new designs that include operations:
https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/dashboard?seid=5b401f4576f3ae2f2fec46b6

Please let me know if you have any questions. Dominika was working on a branch called "Transactions" so you can take it over from there.

**Comment by umurb** [comment]
@developer0623 

Is it possible to show the 'Delegation operations' in the transactions tab?

For example; when I change the address I am delegating to, nothing gets logged in the transaction tab. Can we track the delegation change operations?

**Comment by umurb** [comment]
Merged with #266
