### ISSUE TITLE
Add localization support

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Tezori#161]
As the wallet will be used by people around the world, we will need to provide deployments in multiple languages. Therefore, we need to add localization support. Please note localization should be done statically rather than dynamically, i.e. at build time such that we produce a separate build for each language.

**Comment by vishakh** [comment]
@yanivkalfa Any suggestions?

**Comment by LMilfont** [comment]
Do you guys need a translation to brazilian portuguese? I can help with that.

**Comment by LMilfont** [comment]
Do you have a xml or json file with the string constants of the app messages in english so that I can translate for you? Just send me or point me the file on the directory structure.

**Comment by vishakh** [comment]
@LMilfont Not yet. It will take some time to implement localization. We will let you know when done.

**Comment by umurb** [comment]
Packaging the build exposes the localization keys not localized text

**Comment by umurb** [comment]
Packaging issue resolved with PR #292 
We now have localization support.
