### ISSUE TITLE
List the Delegated Addresses in the order of creation

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#209]
Currently wallet lists the Delegated Addresses in reverse alphabetical order of the Public Address. As soon as the user creates a new delegated address, it most probably messes up the listing of the addresses, causing confusion.

We need to sort the delegated addresses in the order of creation.

**Comment by prashantpawar** [comment]
Did more investigation on this issue and figured out that we don't list the Delegated Addresses in the order of creation (thereby following their numerical order 'Delegate Address 1/2/3', rather we display them in reverse alphabetical order of the Public Address.

So KT1WL23yqjq1ePZLB7vNKa65UvnAk9qd5SNP is displayed before KT1AjkPQ6r6BWgmGHtaza6KZecri3QB7wA3i

**Comment by umurb** [comment]
Merged with #298
