### ISSUE TITLE
Set proper branding on Electron

### ISSUE THREAD

**Issue by yourcodesucks** [Cryptonomic/Tezori#215]
- Customize package icon.
- Customize documentation and other URLs from the Help menu.
- Set proper license and copyright information.
- Set application name.
- It would be nice to build package.json as part of the build process to make sure the build versions match.

**Comment by umurb** [comment]
Below comments are from our current production build;

**Mac**
Name displayed in Menu Bar is 'galleon-prod', should be 'Galleon'
Dropdown menu says About Tezori and Hide Tezori. Should be; About Galleon and Hide Galleon
![screen shot 2018-07-15 at 10 52 04 pm](https://user-images.githubusercontent.com/37525692/42741750-f9d27956-8882-11e8-9a30-3d27e213be64.png)

**Windows**
Name displayed in Task Manager is galleon-prod. Should be Galleon
Electron's default logo is showing up. Should be replaced with Galleon's logo

Task Manager Screen Shot;
![screen shot 2018-07-15 at 11 02 04 pm](https://user-images.githubusercontent.com/37525692/42741792-5d983e6c-8883-11e8-990a-4f75f516ace6.png)

Incorrect Logo Screenshot;
![screen shot 2018-07-15 at 10 53 12 pm](https://user-images.githubusercontent.com/37525692/42741834-b5092094-8883-11e8-9e81-7649abfaea58.png)
