### ISSUE TITLE
Correctly link to block explorers

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Tezori#218]
The links to TZscan have to be sensitive to the network the wallet is running against. In development, the wallet runs against `zeronet` while in production it will run against `betanet`. The link to TZScan will change depending on the network. 

We have to add a field in `app/config.json` called `network`. By default, the value should be `zeronet`. In production, it will be `betanet`.

This is the zeronet URL for an operation ID - http://zeronet.tzscan.io/{operation_id}
This is the betanet URL for an operation ID - http://tzscan.io/{operation_id}

The  correct URL should be used based on the `network` field.

**Comment by umurb** [comment]
Merged with #241
