### ISSUE TITLE
'Create Wallet File': Fix styling in build

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#244]
Create Wallet File renders incorrectly.

_Note: This is a build specific issue. It does not happen in master/develop_

**Currently:** 
![incorrect-create wallet file](https://user-images.githubusercontent.com/37525692/42726383-5bd6a762-8761-11e8-9cca-066ee8139816.png)

**Should be:**
![correct-create wallet file](https://user-images.githubusercontent.com/37525692/42726384-5fe0efe8-8761-11e8-8d74-425e749897d5.png)

**Comment by yanivkalfa** [comment]
the image got moved to the top, the button is all messed up, it should not have 3 lines
it has to look like on test or prod
