### ISSUE TITLE
Display 'Burn' for 'Origination Operation'

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#262]
We need to display the 'burn' for origination operation, preferably in the transactions tab.

@polinasoshkina can you please update origination operation's design in transactions tab so that we display the burn?

Current view is as follows. Below origination operation actually burnt 2 tz!
![screen shot 2018-07-17 at 12 28 58 pm](https://user-images.githubusercontent.com/37525692/42831790-49896d3e-89bd-11e8-9587-be81eb2cd514.png)

We can maybe utilize the 0.000000 tz section?

**Comment by polinasoshkina** [comment]
this should go together with displaying gas.

**Comment by umurb** [comment]
Notes for @developer0623 
1 - Burn will only be displayed in 'origination' operations
2 - It is a constant of 0.257 tz (will actively query the blockchain in later releases)
3 - Every address in transactions tab to be displayed as; 12chars-3dots-12chars

Below is the design;

![screen shot 2018-07-30 at 7 05 41 am](https://user-images.githubusercontent.com/37525692/43377073-32d367f2-93c7-11e8-9472-ae6c8def8aae.png)

https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/screen/5b401f346a9628231aa648d6

**Comment by umurb** [comment]
Merged with #297
