### ISSUE TITLE
Open an existing wallet - Add a hide/show button to password screen

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#268]
There is no option to hide/show password in Open an Existing Wallet scene. We need to add it.

Currently;
![screen shot 2018-07-18 at 12 35 47 pm](https://user-images.githubusercontent.com/37525692/42895247-4c3c9572-8a87-11e8-95e4-4a6620a8b4b4.png)

Should be;
![screen shot 2018-07-18 at 12 35 41 pm](https://user-images.githubusercontent.com/37525692/42895255-53b9e520-8a87-11e8-9ed0-14308ccd38ab.png)

**Comment by umurb** [comment]
@polinasoshkina 

2 questions;

1 - Should we have a hide/show option in every Password field? e.g. there is no show/hide options at the confirmation Modals

2 - Should we replace the eye icon with 'Show/Hide' words in every Password field?

**Comment by polinasoshkina** [comment]
@umurb yes and yes. I felt frustrated many times when typing the wallet password for transactions or delegation and not being able to see where the typo is.

**Comment by umurb** [comment]
Perfect, I'll leave a review for Joe and ask him to fix it everywhere

**Comment by umurb** [comment]
Merged with #271
