### ISSUE TITLE
As a user, I want to be reassured that it's safe for me to enter my seed phrase

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezori#29]
We need to provide some messaging that explains why we need the seed phrase and what we'll do with it:
"We use seed phrase to display your account in the wallet. We don't have access to your seed phrase and never will!"

**Comment by umurb** [comment]
Please let me know if you still want to add this message and I'll move this issue to our Polish Board.

If not, let's close it!
