### ISSUE TITLE
Improve the send tab sending all funds and fee calculations.

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezori#300]
Implement the same "use max" and total and remaining balance functionality as in Add Delegate Modal (except there is no gas when sending transactions).

Design:
https://zpl.io/bPY38om

**Comment by umurb** [comment]
Update the warning message;

**Manager Address sending funds**
if; remaining balance == 0.000000
then; warning message = 'Manager Addresses are not yet allowed to have less than 1 µtz'

else if; remaining balance < 0.000000
then; warning message = 'Total exceeds available funds'

**Delegated Address sending funds**
if; remaining balance <= 0.000000
then; warning message = 'Total exceeds available funds'

**Comment by umurb** [comment]
Merged with #306
