### ISSUE TITLE
15-Word Seed Auto complete 

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezori#31]
Since prototype didn't test any data entry, we should follow best practices for entering seed words:
1. Provide autocomplete selection for each word to avoid spelling arrows or use of the words that are not on the list
2. Provide numbering of words so that user can easily cross-reference the entry.

**Comment by umurb** [comment]
Design: https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/dashboard?seid=5b51fc653d8b933b05367ee8

List of words: https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

**Comment by umurb** [comment]
Upgrading Material UI from 0.x to 1.x globally would cost us 2 days. According to [Material-UI Github](https://github.com/mui-org/material-ui/issues/7195) we can use two different versions of this package at the same time.

Let's isolate the 15-word seed input box as a component and use the next version of Material-UI only in this component and see if it goes through.

**Comment by umurb** [comment]
Merged with #290
