### ISSUE TITLE
Wallet should default to 24 words not 15

### ISSUE THREAD

**Issue by murbard** [Cryptonomic/Tezori#330]
24 words provide more entropy, more checksum bits and are the default on Ledger devices. Support for 15 word mnemonics from TezBox makes sense, but it would be sad if this ecosystem started to myopically standardize around 15 words.

**Comment by umurb** [comment]
Makes a lot of sense. Will discuss with the team and see if we can include this in R3

**Comment by anonymoussprocket** [comment]
Resolved in 0.8.4 branch.
