### ISSUE TITLE
Wallet password creation should not show time estimates

### ISSUE THREAD

**Issue by murbard** [Cryptonomic/Tezori#331]
Tezori displays a message when picking a wallet indicating "how long it will take to crack". This does not make a whole lot of sense... first of all cracking is highly parallel, so the right estimate would be in CPU hours, not hours. Second, the estimation of the entropy is naive and could lull a user picking a long but weak password into a false sense of security.

**Comment by umurb** [comment]
I thought the estimate was somewhat correct, thanks for the warning. Although it is such a cute little message which makes the wallet more user-friendly, we will remove it in the next release.

**Comment by murbard** [comment]
With all due respect, I mentioned it after the first release and it's potentially a security issue.

**Comment by umurb** [comment]
Merged with #376
