### ISSUE TITLE
Issue with autocompletion when inputing a mnemonic

### ISSUE THREAD

**Issue by murbard** [Cryptonomic/Tezori#332]
Auto-completion does not word when a word is being repeated. To reproduce try entering "zebra" and then "zebra" again.

**Comment by umurb** [comment]
@developer0623 please allow same words to be used when importing an account by not removing the words from autocomplete list

![screen shot 2018-08-17 at 4 31 00 pm](https://user-images.githubusercontent.com/37525692/44288116-332b9880-a23d-11e8-8f3e-cd2643f4dfaa.png)

**Comment by umurb** [comment]
Merged with #334
