### ISSUE TITLE
Page numbers needs a better representation

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#352]
![galleon-paging](https://user-images.githubusercontent.com/37525692/44678927-966cb600-aa07-11e8-97dc-142b9c0d4934.png)

A user with 600+ transactions shared this screenshot. The user is now required to scroll right to see transaction values due to the long list of pages. We need a better way of representing pages.

I suggest using a dotted representation after 10th page.
**i.e;** 1 2 3 4 . . . 45 46 47

@polinasoshkina Do you have a better idea than dots?

**Comment by polinasoshkina** [comment]
Display simpler pagination at the bottom right corner:
https://zpl.io/2jw5L8r

Here are disabled and hover states:
https://zpl.io/2GOGkQ4

Rules:
- Pagination should only appear when there is more than one page
- Left arrow will be disabled on the first page
- Right arrow will be disabled on the last page
- Pagination label displays the ranger of results on the page and overall number of transactions (e.g. 1-5 of 23)

**Comment by umurb** [comment]
Merged with #354
