### ISSUE TITLE
Implement the new design for Settings Page

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#365]
Design:
https://app.zeplin.io/project/5b1752dd44fc7a0363cd9dc8/screen/5b8707139458d40928f3638d

**Comment by umurb** [comment]
@polinasoshkina approve the implementation?

![screen shot 2018-09-05 at 11 23 47 am](https://user-images.githubusercontent.com/37525692/45103695-766f7d80-b0fe-11e8-898a-5a245dee0f0f.png)

**Comment by polinasoshkina** [comment]
Looks good, how is the drop-down looking inside?

**Comment by umurb** [comment]
@polinasoshkina 

![settings](https://user-images.githubusercontent.com/37525692/45108360-62ca1400-b10a-11e8-97d6-7224e2406753.gif)

**Comment by umurb** [comment]
Merged with #390
