### ISSUE TITLE
Allow for opening wallet with seed words

### ISSUE THREAD

**Issue by Sm00g15** [Cryptonomic/Tezori#392]
Users should be able to open the wallet by using the seedwords, as well as the password.

**Comment by nyeates** [comment]
I want to second importance of this. I am supporting a colleague who has run into wanting to restore wallet due to password not working and now seed wont work either.  Is it a known issue?... or should it be working in .2?

**Comment by umurb** [comment]
v0.2.0b and up allow users to restore their accounts using their 15-word seed phrase. 

![screen shot 2018-10-03 at 10 19 51 am](https://user-images.githubusercontent.com/37525692/46416594-e3723500-c6f5-11e8-92df-bda92cd8747c.png)

In case of a lost password, users should be able to recover your funds using this feature.
