### ISSUE TITLE
Some amounts throw a 'String does not look like hex data' error

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#394]
MacOS - Galleon v0.2.0

Steps to reproduce;
Try sending `16.1` or `4.02` tz to an account;

![screen shot 2018-09-19 at 10 32 09 am](https://user-images.githubusercontent.com/37525692/45760406-f960ff80-bbf7-11e8-897e-e14337eeed42.png)

**Comment by Ogletree** [comment]
Windows - Galleon v0.3.0b
Hmmm, now having the issue sending 8.13

**Comment by developer0623** [comment]
The issues are related to Javascript Mistakes.

**Comment by umurb** [comment]
Merged with #398
