### ISSUE TITLE
Retrieving Account: Do not spin the refresh icon

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#419]
At the moment, 4 different spinners are spinning by the time of retrieving an account.
![retrieving](https://user-images.githubusercontent.com/37525692/46959389-e6f8ab00-d069-11e8-873f-906343bdacc3.gif)
Issue #418 will get rid of the white bubbles, but we need to stop refresh icon from spinning during wallet is retrieving or preparing an account.

**Comment by umurb** [comment]
@polinasoshkina we were able to reduce the spinners down to 2. Do you have any other improvement suggestions or should I merge it as is?

![spinners](https://user-images.githubusercontent.com/37525692/47048242-d0d11480-d167-11e8-9d64-517caef342e5.gif)

**Comment by polinasoshkina** [comment]
Did we fix the 'last updated" one as well? Will it start spinning when it's
refreshing and will it start spinning when I click on it to manually
refresh?

**Comment by umurb** [comment]
Yes, PR #427 fixes that as well. No white bubble will spin on the middle of the screen, only the refresh icon will spin at the time of manual or automatic refresh

**Comment by umurb** [comment]
Merged with #427
