### ISSUE TITLE
Utilize Enter Key to trigger buttons

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#423]
Enter key should trigger below buttons;

1 - LoginCreate - Create New Wallet button
2 - LoginImport - Open button
3 - AddDelegateModal - Delegate button
4 - SendConfirmationModal - Confirm button
5 - ChangeDelegateModal - Change Delegate button

**Comment by Sm00g15** [comment]
@developer0623 can I get an apiKey for the Tezos/Conseil nodes to finish up 3-5 above? I couldn't find you on Riot

**Comment by umurb** [comment]
merged with #430
