### ISSUE TITLE
Fix Import Fundraiser Account scene by adding autocomplete and word parsing

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#441]
The UX we offer in `Import Fundraiser Wallet` scene is not as good as `Restore from Backup` scene.

There are 2 common user approaches in `Import`

1. Enter the 15-word phrase one by one

In this case, we should offer the same autocomplete functionality we are offering with `Restore`

2. Copy paste the 15-word phrase

In this case, as soon as user switches focus from this input box Galleon should parse the pasted 15-word and display errors in red

If all is good it should look like;

![success](https://user-images.githubusercontent.com/37525692/47516818-6baaac80-d854-11e8-8340-9665c929b8e8.png)

If there is an error, it should look like;

![fail](https://user-images.githubusercontent.com/37525692/47516836-76fdd800-d854-11e8-8532-4b8759dcb4e6.png)

_Notes:_
Error fixing experience needs to be fixed. It will be handled in another ticket.

**Comment by Sm00g15** [comment]
I've fixed and implemented #1, working on #2 now

**Comment by umurb** [comment]
Merged with #499
