### ISSUE TITLE
send operation failed

### ISSUE THREAD

**Issue by ilya272** [Cryptonomic/Tezori#536]
https://pp.userapi.com/c847121/v847121653/14d62b/pDyeSKe6dEs.jpg

https://tzscan.io/tz1MSSnDxcLqvQpJuXZ4hxmQbwuCcE5aDZR8

send operation failed

What to do?

**Comment by umurb** [comment]
Hi @ilya272 
I am guessing that you are using v0.5.0b. Please upgrade to v0.6.0b to send this operation.

The account you are trying to send is an implicit account with 0 balance, which requires you to burn 0.257 tz. 

Try sending MAX_AVAILABLE_BALANCE - FEE - 0.257 - 0.000001 and your transaction will go through. 

In your case: 537.025526 - 0.01420 (fee) - 0.257 - 0.000001 (v0.5.0b does not allow emptying out implicit accounts) = **536.754325**

**Comment by AlexWinner1** [comment]
Hello, I have a problem "send operation failed"  sending from my wallet Galleon v0.2.0b.
If I understand correctly, I need to update my wallet. How to do it?
And what else needs to be done?

**Comment by umurb** [comment]
Please visit https://galleon-wallet.tech to download and setup the most recent version. Your transaction will go through after you upgrade it.
