### ISSUE TITLE
I cant Send Tezos to Exchanges

### ISSUE THREAD

**Issue by Cachtio56** [Cryptonomic/Tezori#551]
I unsuccessfully tried to send Tezos 4 times to exchange accounts. Things looks when I click the "Send" button but the transactions fail. I increase the fee to 0.01 and didn't work.
What is wrong? I'll appreciate your help.

**Comment by umurb** [comment]
I am assuming this is a Galleon related question, if so please send an e-mail to support@cryptonomic.tech in the future for faster responses.

Are you using the most recent version (v0.6.1b) of the wallet? Most of the older versions are now out of service due to the recent Protocol 003 upgrade
