### ISSUE TITLE
add screenshots to readme

### ISSUE THREAD

**Issue by amilajack** [Cryptonomic/Tezori#553]
I think it would be useful to users if screenshots could be added to the readme so that they can get an idea of what the app is before using it. I can PR for this. Would that be a we welcome change?

**Comment by vishakh** [comment]
Hello Amila,

Tezori is a community-driven open source project so your improvements would
be very helpful. Feel free to join our Riot chat at
https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=ostez.com
if
you want to discuss the details.

**Comment by amilajack** [comment]
Are there any screenshots that already exist? If not can you please share some here. I wasn't able to get the app up and running

**Comment by anonymoussprocket** [comment]
Closing as it appears to be abandoned.
