### ISSUE TITLE
Ledger Nano S address is other with the same path

### ISSUE THREAD

**Issue by gawlea** [Cryptonomic/Tezori#555]
I have a question, why the addresses are different on (TezBox and Galleon) when using the same path on a Ledger Nano S.

Is this an issue?

**Comment by umurb** [comment]
Hi,

Thanks for reaching out. Going forward, please send your Galleon related questions to support@cryptonomic.tech.

I've just tried this issue out with a random derivation path `44'/1729'/3'/2'/1'` and got the exact same address on both Galleon and TezBox.
Are you certain that the path you selected is identical in both wallets? Cause TezBox defaults into `44'/1729'/0'/0'` and Galleon defaults into `44'/1729'/0'/0'/'0`

![screen shot 2019-01-16 at 9 57 35 am](https://user-images.githubusercontent.com/37525692/51257461-ac0e5800-1975-11e9-8f19-0cdb9310c3bc.png)
![screen shot 2019-01-16 at 9 58 33 am](https://user-images.githubusercontent.com/37525692/51257462-ac0e5800-1975-11e9-8d5a-f589029097c0.png)

**Comment by gawlea** [comment]
I am sure that the path is the same 44'/1729'/0'/0' anyway I'll try another path to see if I had the same issue.

**Comment by anonymoussprocket** [comment]
closing as it appears to be resolved.
