### ISSUE TITLE
Adjust Tezori to query Conseil at the time of Login and get the network name

### ISSUE THREAD

**Issue by anonymoussprocket** [Cryptonomic/Tezori#564]
Conseil v2 API needs a network parameter to execute queries. By the time of login, Tezori should query Conseil and get the available network names for `Tezos` platform, and use this network name through out.

**Comment by anonymoussprocket** [comment]
This would need to happen if/when conseil node configuration changes in the settings view as well.

**Comment by umurb** [comment]
Merged with #568
