### ISSUE TITLE
Warn the user about smart contract interactions not being trustless

### ISSUE THREAD

**Issue by umurb** [Cryptonomic/Tezori#591]
ConseilJS is not yet capable of locally forging smart contract interaction operations. Until we figure out a way to locally forge them, smart contract interactions will be forged on server-side and will require a trust to the selected Tezos node. We need to warn the user about this.

When the user selects **Interact with Contracts** for the first time, we should first check the selected Tezos Node of the user.

If the Tezos Node URL **does not** contain the word `localhost`, we should show the user the following warning message:

![OPzMmnwJNcPMlVljJLDqiWJz](https://user-images.githubusercontent.com/37525692/55925272-103e6200-5bdb-11e9-92af-074c7c8f0670.png)
Design: https://share.goabstract.com/6a26b044-e469-4346-9446-772775262281

---

The message changed slightly:

**Security Notice**

It looks like you are not running a local Tezos node. It's perfectly fine to use a hosted node. However, if the Tezos node is compromised, you might end up losing your funds. **Learn More**

---

 - [x] Proceed button should be enabled only if the **I understand that this operation..** checkbox is checked.
- [x] If the user selects cancel, do not open InteractContractModal
- [x] If the user checks **Don't show me this again..** the checkbox, record this selection in localStorage or walletSettings, and do not show the message again.
- [x] Learn more button will open up an external (possibly medium.com) link. I will provide this later

**Comment by umurb** [comment]
@developer0623 any questions on this ticket? You can reach out to me via e-mail during the time riot is down. I already sent one to you

**Comment by developer0623** [comment]
@umurb currently, I have no question.
I'm working on the UI, now.

**Comment by umurb** [comment]
@developer0623 here is the URL for Learn More button:

https://github.com/Cryptonomic/Deployments/wiki/Galleon:-FAQ#smart-contracts

**Comment by umurb** [comment]
Merged with #594
