### ISSUE TITLE
Galleon release 0.8.1b complains that I'm not running 0.8.1b

### ISSUE THREAD

**Issue by murbard** [Cryptonomic/Tezori#611]
![image](https://user-images.githubusercontent.com/1591742/59353962-f9021a80-8cd8-11e9-913a-9da30b9e1d01.png)

**Comment by murbard** [comment]
I realize this is the repo for Tezori, so I don't know if this specific Galleon bug is in the right place, if not please point me to it.

**Comment by anonymoussprocket** [comment]
This was resolved in 0.8.2.
