### ISSUE TITLE
Galleon wallet builds should include alphanet selection (easy way to switch to alphanet)

### ISSUE THREAD

**Issue by cryptofuture** [Cryptonomic/Tezori#626]
- Galleon wallet builds should include alphanet selection

Basically this would make payment testing for development easier.
Also I couldn't understand why production(mainnet) network connection details hidden and not mention anywhere in the doc, as nothing prevents me from unpacking and using those directly

On the other side running conseil server for the mainnet is troublesome

Basically right now galleon even prevents me from connecting the node I add manually, as it requires https.

**Comment by cryptofuture** [comment]
Yes, also it seem that custom nodes are not saved after wallet close, so the correct way would be to copy the config file somewhere in the home directory, and use to load from it after.

**Comment by anonymoussprocket** [comment]
They are included as of 091. Thank you for the suggestion.
