### ISSUE TITLE
Send button disable with over 5k tezos on account

### ISSUE THREAD

**Issue by switchezcrypto** [Cryptonomic/Tezori#653]
Hello,

I have succesfully transfered ico tezos to galleon wallet with ledger nano s last April.

Now, after few months,i  was trying to send some tezos to exchange, but "SEND" button is always disable, no matter how many fee i choose, even if i click "reveal secret key", nothin appear, or if i chose a delegate, nothing happen.

Looks like a major general stuck.

I use ledger nanos attached to galleon.

Already tried with latest galleon version and also some previous ones as well as other pc (both windows 10 or windows 7)

![immagine](https://user-images.githubusercontent.com/57045419/68541662-a1a8c900-03a2-11ea-822f-907b1a39b58f.png)

**Comment by anonymoussprocket** [comment]
Please get in touch via one of our support channels via email or telegram.
