### ISSUE TITLE
Wallet Balance

### ISSUE THREAD

**Issue by raleighnc** [Cryptonomic/Tezori#661]
I recovered my balance fine from Bakechain.  however all the deposits which were locked up can now be transfered.  the balance on galleon wallet isn't showing the correct balance as tzstats or bakechain.
(and i waited 2 weeks, i only have 192xtz still on deposit the other XTZ should be available.   why is the balalnce not correct?  Do i really have to go through the entire import and activation again??

**Comment by anonymoussprocket** [comment]
Hi, we need more information. Please reach out on one of our support channels.
