### ISSUE TITLE
This account has 0 balance or doesn't exist

### ISSUE THREAD

**Issue by khalidmahmood001** [Cryptonomic/Tezori#670]
Hi,
I loaded XTZ from my paper wallet to Galleon Wallet.
I am trying to fund my kraken XTZ account from Galleon. When I specify the recipient address (provided by Kraken), I get message:
This account has 0 balance or doesn't exist
Any thoughts? I bought 10 XTZ in Kraken to ensure it was not '0' balance and still had same issue.

Thanks

**Comment by anonymoussprocket** [comment]
The Tezos chain doesn't keep 0-balance accounts under some circumstances, if you're certain the address you're sending to is correct, you can proceed with the transfer. This is not a error, it's a warning.
