### ISSUE TITLE
"Connection refused by Ledger" - Galleon wallet to Ledger Nano X

### ISSUE THREAD

**Issue by Evisugene** [Cryptonomic/Tezori#671]
Hi,

I am trying to use the Connect with Ledger to open a Galleon account.

However I get the message "Connection refused by Ledger": https://www.screencast.com/t/ZMeMu9ylVE

Any ideas? Also I can include logs if there is an option for that, couldn't find one.

Thank you

**Comment by anonymoussprocket** [comment]
Find us on the [Galleon user support chat](https://t.me/cryptonomicGalleonUsers).
