### ISSUE TITLE
Galleon Origination operation failed

### ISSUE THREAD

**Issue by bharathraj1992** [Cryptonomic/Tezori#674]
Hello,
I am trying to add a new delegate but I am getting "Origination operation failed" error. Can you please help me

**Comment by razorhash** [comment]
I have the same issue!

**Comment by anonymoussprocket** [comment]
Hi guys, I'll need a lot more detail. If you haven't already, find us on the [Riot developer chat](https://matrix.to/#/!rUwpbdwWhWgKINPyOD:cryptonomic.tech?via=cryptonomic.tech&via=matrix.org&via=tzchat.org).
