### ISSUE TITLE
Can't create new wallet file

### ISSUE THREAD

**Issue by edwinportillo21** [Cryptonomic/Tezori#676]
I downloaded Galleon and am a new user. I went to create a Galleon wallet and it only lets me select a wallet file it does not give me the option to create a new one. Same thing happens when I click create new wallet, no option to create and save a file. Only the option to open an existing one. I need to be able to create one in order to create an account an send my tezos ico coins.

**Comment by anonymoussprocket** [comment]
That button selects a file destination for a new file, the wording of that button is altered in the next release.
