### ISSUE TITLE
Make settings editable

### ISSUE THREAD

**Issue by vishakh** [Cryptonomic/Tezori#727]
The app already has a rudimentary Settings screen:

![image](https://user-images.githubusercontent.com/931163/169237083-b8505171-1633-42a1-b52b-4ce313259ce1.png)

The values from Settings are used to query account balances, etc:

![image](https://user-images.githubusercontent.com/931163/169237234-f9952077-efe3-4ff3-896c-c70ac567dd02.png)

We now want to make the items in the Settings screen editable:
- [ ] Ensure the Settings items are editable
- [ ] Add a button to apply changes by the user
- [ ] Ensure that the global state is updated accordingly

**Comment by amardeepio** [comment]
![Screenshot_20220526_141216](https://user-images.githubusercontent.com/2884176/170701583-374de942-cba3-4833-b4ed-24aeffdb501a.png)

the **apply changes** button does chnage the state but accunts info arent showing accordingly
