### ISSUE TITLE
Master branch activation codes are in base-58 not hexadecimal

### ISSUE THREAD

**Issue by polinasoshkina** [Cryptonomic/Tezori#93]

**Comment by skaht** [comment]
I'm completely disappointed that KYC/AML activation codes for ICO end users are currently in hex format (this is something I would expect from Ethereum, not Tezos) instead of being base58check-encoded to minimize the chances of ICO users from making typo mistakes when they configure their wallets for the first time! 

Will already generated KYC/AML activation codes be redistributed online in [**base58check-encode**](https://github.com/libbitcoin/libbitcoin-explorer/wiki/bx-base58check-encode) format?

**Comment by vishakh** [comment]
@skaht Check out https://github.com/Cryptonomic/ConseilJS/blob/efb35a2982b9677042944d8d7a637a299d96d7af/src/tezos/TezosWallet.ts#L92 for generating private keys from activation codes.

**Comment by vishakh** [comment]
@skaht We can't comment on the format of the activation codes. Please check with the Tezos dev team.

**Comment by skaht** [comment]
@vishakh - thanks for pointing to the L92:-)  

Until the new KYC/AML activation codes, only the **BIP 39 seed words**, investor **email address** used during the ICO, and the investor **password** used during the ICO were required to back into private seeds associated with the ICO.  

The public key hash can be synthesized from from the private key, see code at and around https://github.com/tezos/fundraiser-tools/blob/master/pykeychecker/keychecker.py#L45. Hence the **unlockFundraiserIdentity** function input argument **pkh: string** might not be needed.

I'm confident  KYC/AML activation codes will ultimately impact **unlockFundraiserIdentity** .

**Comment by vishakh** [comment]
@skaht The `pkh` argument was recently added to ensure the user is unlocking the correct account. It's possible for the user to input one incorrect seed word and still end up with a valid Tezos address, just not the one they wanted. It will likely have zero balance and also refuse to activate. Think of it purely as a mitigation.

Yes, we expect an impact on that function and we will change the logic (maybe it's just a Base58Check decode) to accommodate the format change.

**Comment by skaht** [comment]
It is true a 15 word BIP 39 seed will only have 5 checksum bits. You are correct in asserting 5 checksum bits is not adequate from an end user perspective.

Let's hope it is a Base58Check-decode can be used.  However, the Tezos Core Team needs to ensure the AML/KYC activation codes are Base58Check-encoded.

**Comment by skaht** [comment]
@vishakh - From https://stephenandrews.github.io/activatez/ and https://www.reddit.com/r/tezos/comments/8v5qbr/commands_to_activate_fundraiser_accounts_with/, its looking like Tezos AML/KYC activation might be purely a network things that will be decoupled from **unlockFundraiserIdentity** behaviors. My original assertion might have been wrong. Do you concur?

**Comment by umurb** [comment]
Closing this issue since this issue can only be fixed (could have been avoided) by the Tezos core team.
